resources:
  - name: chat-service
    type: git
    check_every: 30m
    source:
      branch: master
      uri: ((git-uri))
      private_key: ((publishing-outputs-private-key))

jobs:
  - name: package
    public: true
    plan:
      - get: chat-service
        trigger: true
      - task: Package project
        file: chat-service/automation/ci/tasks/package.yml
      - put: deploy-cf
        params:
          manifest: build-output/manifest.yml
          environment_variables:
            SPRING_PROFILES_ACTIVE: ((dev-env))
