resources:
  - name: repo
    type: git
    source:
      uri: ((git-uri))

    - name: deploy-cf
      type: cf
      source:
        api: https://api.run.pivotal.io
        username: ((cf-login))
        password: ((cf-password))
        organization: chat-service
        space: development
        skip_cert_check: false

jobs:

  jobs:
    - name: unit-test
      plan:
        - get: repo
          trigger: true
        - task: mvn-test
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: maven
            inputs:
              - name: repo
            caches:
              - path: repo/m2
            run:
              path: bash
              args:
                - -c
                - |
                  set -e
                  cd repo
                  rm -rf ~/.m2
                  ln -fs $(pwd)/m2 ~/.m2
                  mvn test
    - name: build-and-deploy
      plan:
        - get: repo
          passed:
            - unit-test
          trigger: true
        - task: mvn-package
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: maven
            inputs:
              - name: repo
            outputs:
              - name: build
            caches:
              - path: repo/m2
            run:
              path: bash
              args:
                - -c
                - |
                  set -e
                  cd repo
                  rm -rf ~/.m2
                  ln -fs $(pwd)/m2 ~/.m2
                  mvn package -DskipTests=true
                  mv target/ROOT.jar ../build
        - put: cf
          params:
            manifest: repo/manifest.yml
            path: build/ROOT.jar
            current_app_name: hello-servlet