---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

inputs:
  - name: build-output

run:
  path: "chat-service/automation/cd/tasks/deploy.sh"
  args: ["build-output"]
