resources:
  - name: chat-service
    type: git
    check_every: 30m
    source:
      branch: master
      uri: ((git-uri))
      private_key: ((publishing-outputs-private-key))

  - name: deploy-cf
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: ((cf-login))
      password: ((cf-password))
      organization: chat-service
      space: development
      skip_cert_check: false

jobs:
  - name: build
    public: true
    plan:
      - get: chat-service
        trigger: true
      - task: Build project
        file: chat-service/ci/tasks/build.yml
      - put: deploy-cf
        params:
          manifest: build-output/manifest.yml
